# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Syringe_pump.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(647, 319)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 160, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_godefault = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_godefault.sizePolicy().hasHeightForWidth())
        self.pushButton_godefault.setSizePolicy(sizePolicy)
        self.pushButton_godefault.setObjectName("pushButton_godefault")
        self.verticalLayout.addWidget(self.pushButton_godefault)
        self.pushButton_run = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.radioButton_withdraw = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_withdraw.setObjectName("radioButton_withdraw")
        self.verticalLayout.addWidget(self.radioButton_withdraw)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 60, 371, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_rate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.gridLayout.addWidget(self.lineEdit_rate, 1, 1, 1, 1)
        self.labe_setratel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe_setratel.sizePolicy().hasHeightForWidth())
        self.labe_setratel.setSizePolicy(sizePolicy)
        self.labe_setratel.setObjectName("labe_setratel")
        self.gridLayout.addWidget(self.labe_setratel, 0, 1, 1, 1)
        self.label_selectpump = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selectpump.sizePolicy().hasHeightForWidth())
        self.label_selectpump.setSizePolicy(sizePolicy)
        self.label_selectpump.setObjectName("label_selectpump")
        self.gridLayout.addWidget(self.label_selectpump, 0, 0, 1, 1)
        self.spinBox_selectpump = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_selectpump.setObjectName("spinBox_selectpump")
        self.gridLayout.addWidget(self.spinBox_selectpump, 1, 0, 1, 1)
        self.label_current = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_current.setObjectName("label_current")
        self.gridLayout.addWidget(self.label_current, 4, 0, 1, 1)
        self.lineEdit_volume = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.gridLayout.addWidget(self.lineEdit_volume, 3, 0, 1, 1)
        self.label_setvolume = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_setvolume.setObjectName("label_setvolume")
        self.gridLayout.addWidget(self.label_setvolume, 2, 0, 1, 1)
        self.lcdNumber_current = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_current.sizePolicy().hasHeightForWidth())
        self.lcdNumber_current.setSizePolicy(sizePolicy)
        self.lcdNumber_current.setObjectName("lcdNumber_current")
        self.gridLayout.addWidget(self.lcdNumber_current, 5, 0, 1, 1)
        self.label_voldisp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_voldisp.setObjectName("label_voldisp")
        self.gridLayout.addWidget(self.label_voldisp, 4, 1, 1, 1)
        self.lcdNumber_voldisp = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_voldisp.sizePolicy().hasHeightForWidth())
        self.lcdNumber_voldisp.setSizePolicy(sizePolicy)
        self.lcdNumber_voldisp.setObjectName("lcdNumber_voldisp")
        self.gridLayout.addWidget(self.lcdNumber_voldisp, 5, 1, 1, 1)
        self.pushButton_setdefault = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setdefault.setFont(font)
        self.pushButton_setdefault.setObjectName("pushButton_setdefault")
        self.gridLayout.addWidget(self.pushButton_setdefault, 3, 1, 1, 1)
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 25))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.pushButton_godefault.setText(_translate("Form", "Goto default"))
        self.pushButton_run.setText(_translate("Form", "Run!"))
        self.pushButton_stop.setText(_translate("Form", "Stop"))
        self.radioButton_withdraw.setText(_translate("Form", "Withdraw"))
        self.labe_setratel.setText(_translate("Form", "set rate"))
        self.label_selectpump.setText(_translate("Form", "select pump"))
        self.label_current.setText(_translate("Form", "Current rate"))
        self.label_setvolume.setText(_translate("Form", "set volume"))
        self.label_voldisp.setText(_translate("Form", "volume dispensed"))
        self.pushButton_setdefault.setText(_translate("Form", "Set as default!"))

