# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Syringe_pump.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 528)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 160, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_godefault = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_godefault.sizePolicy().hasHeightForWidth())
        self.pushButton_godefault.setSizePolicy(sizePolicy)
        self.pushButton_godefault.setObjectName("pushButton_godefault")
        self.verticalLayout.addWidget(self.pushButton_godefault)
        self.pushButton_setdefault = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setdefault.sizePolicy().hasHeightForWidth())
        self.pushButton_setdefault.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setdefault.setFont(font)
        self.pushButton_setdefault.setObjectName("pushButton_setdefault")
        self.verticalLayout.addWidget(self.pushButton_setdefault)
        self.pushButton_run = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.radioButton_withdraw = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_withdraw.setObjectName("radioButton_withdraw")
        self.verticalLayout.addWidget(self.radioButton_withdraw)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 30, 421, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_setvolume = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_setvolume.setObjectName("label_setvolume")
        self.gridLayout.addWidget(self.label_setvolume, 3, 0, 1, 1)
        self.lineEdit_rate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.gridLayout.addWidget(self.lineEdit_rate, 2, 1, 1, 1)
        self.label_selectpump = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selectpump.sizePolicy().hasHeightForWidth())
        self.label_selectpump.setSizePolicy(sizePolicy)
        self.label_selectpump.setObjectName("label_selectpump")
        self.gridLayout.addWidget(self.label_selectpump, 1, 0, 1, 1)
        self.labe_setratel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe_setratel.sizePolicy().hasHeightForWidth())
        self.labe_setratel.setSizePolicy(sizePolicy)
        self.labe_setratel.setObjectName("labe_setratel")
        self.gridLayout.addWidget(self.labe_setratel, 1, 1, 1, 1)
        self.spinBox_selectpump = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_selectpump.setObjectName("spinBox_selectpump")
        self.gridLayout.addWidget(self.spinBox_selectpump, 2, 0, 1, 1)
        self.lineEdit_volume = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.gridLayout.addWidget(self.lineEdit_volume, 4, 0, 1, 1)
        self.label_current = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_current.setObjectName("label_current")
        self.gridLayout.addWidget(self.label_current, 5, 0, 1, 1)
        self.lcdNumber_current = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_current.sizePolicy().hasHeightForWidth())
        self.lcdNumber_current.setSizePolicy(sizePolicy)
        self.lcdNumber_current.setObjectName("lcdNumber_current")
        self.gridLayout.addWidget(self.lcdNumber_current, 6, 0, 1, 1)
        self.lcdNumber_voldisp = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_voldisp.sizePolicy().hasHeightForWidth())
        self.lcdNumber_voldisp.setSizePolicy(sizePolicy)
        self.lcdNumber_voldisp.setObjectName("lcdNumber_voldisp")
        self.gridLayout.addWidget(self.lcdNumber_voldisp, 6, 1, 1, 1)
        self.label_voldisp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_voldisp.setObjectName("label_voldisp")
        self.gridLayout.addWidget(self.label_voldisp, 5, 1, 1, 1)
        self.label_deltime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_deltime.setObjectName("label_deltime")
        self.gridLayout.addWidget(self.label_deltime, 3, 1, 1, 1)
        self.lineEdit_deltime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_deltime.setObjectName("lineEdit_deltime")
        self.gridLayout.addWidget(self.lineEdit_deltime, 4, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 210, 160, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_adds = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_adds.sizePolicy().hasHeightForWidth())
        self.pushButton_adds.setSizePolicy(sizePolicy)
        self.pushButton_adds.setObjectName("pushButton_adds")
        self.verticalLayout_2.addWidget(self.pushButton_adds)
        self.pushButton_dels = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dels.sizePolicy().hasHeightForWidth())
        self.pushButton_dels.setSizePolicy(sizePolicy)
        self.pushButton_dels.setObjectName("pushButton_dels")
        self.verticalLayout_2.addWidget(self.pushButton_dels)
        self.pushButton_updatepro = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_updatepro.sizePolicy().hasHeightForWidth())
        self.pushButton_updatepro.setSizePolicy(sizePolicy)
        self.pushButton_updatepro.setObjectName("pushButton_updatepro")
        self.verticalLayout_2.addWidget(self.pushButton_updatepro)
        self.pushButton_runpro = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_runpro.sizePolicy().hasHeightForWidth())
        self.pushButton_runpro.setSizePolicy(sizePolicy)
        self.pushButton_runpro.setObjectName("pushButton_runpro")
        self.verticalLayout_2.addWidget(self.pushButton_runpro)
        self.pushButton_savepro = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_savepro.sizePolicy().hasHeightForWidth())
        self.pushButton_savepro.setSizePolicy(sizePolicy)
        self.pushButton_savepro.setObjectName("pushButton_savepro")
        self.verticalLayout_2.addWidget(self.pushButton_savepro)
        self.tableWidget_steps = QtWidgets.QTableWidget(Form)
        self.tableWidget_steps.setGeometry(QtCore.QRect(210, 210, 501, 192))
        self.tableWidget_steps.setMinimumSize(QtCore.QSize(301, 0))
        self.tableWidget_steps.setObjectName("tableWidget_steps")
        self.tableWidget_steps.setColumnCount(5)
        self.tableWidget_steps.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_steps.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_steps.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_steps.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_steps.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_steps.setHorizontalHeaderItem(4, item)
        self.tableWidget_steps.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_steps.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_steps.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_steps.verticalHeader().setStretchLastSection(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 420, 551, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_loadpro = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadpro.sizePolicy().hasHeightForWidth())
        self.pushButton_loadpro.setSizePolicy(sizePolicy)
        self.pushButton_loadpro.setObjectName("pushButton_loadpro")
        self.horizontalLayout.addWidget(self.pushButton_loadpro)
        self.lineEdit_protocol = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_protocol.setObjectName("lineEdit_protocol")
        self.horizontalLayout.addWidget(self.lineEdit_protocol)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_godefault.setText(_translate("Form", "Goto default"))
        self.pushButton_setdefault.setText(_translate("Form", "Set as default!"))
        self.pushButton_run.setText(_translate("Form", "Run!"))
        self.pushButton_stop.setText(_translate("Form", "Stop"))
        self.radioButton_withdraw.setText(_translate("Form", "Withdraw"))
        self.label_setvolume.setText(_translate("Form", "set volume"))
        self.lineEdit_rate.setText(_translate("Form", "5000"))
        self.label_selectpump.setText(_translate("Form", "select pump"))
        self.labe_setratel.setText(_translate("Form", "set rate"))
        self.lineEdit_volume.setText(_translate("Form", "100.00"))
        self.label_current.setText(_translate("Form", "Current rate"))
        self.label_voldisp.setText(_translate("Form", "Volume dispensed"))
        self.label_deltime.setText(_translate("Form", "delivery time (s)"))
        self.lineEdit_deltime.setText(_translate("Form", "220"))
        self.pushButton_adds.setText(_translate("Form", "Add step"))
        self.pushButton_dels.setText(_translate("Form", "Delete step(s)"))
        self.pushButton_updatepro.setText(_translate("Form", "Update protocol"))
        self.pushButton_runpro.setText(_translate("Form", "Run protocol"))
        self.pushButton_savepro.setText(_translate("Form", "Save protocol"))
        item = self.tableWidget_steps.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Delivery time (s)"))
        item = self.tableWidget_steps.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Rate (uL/h)"))
        item = self.tableWidget_steps.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Volume (uL)"))
        item = self.tableWidget_steps.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Status"))
        item = self.tableWidget_steps.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Select"))
        self.pushButton_loadpro.setText(_translate("Form", "Load protocol"))

